# Example mosquitto.conf that configures a local listener with password authentication and defines a TLS bridge to an AWS IoT endpoint to forward espresense topics.
#
# Full tutorial: https://shillehtek.com/blogs/news/esp32-espresense-aws-iot-integration
# Parts used: https://shillehtek.com/products/shillehtek-400-point-breadboard
#             https://shillehtek.com/products/esp32-wroom-dev-board-cp2102-usb-c-presoldered
# More examples: https://github.com/shillehbean/shillehtek-examples
#

listener 1883 0.0.0.0
allow_anonymous false
password_file /opt/homebrew/etc/mosquitto/password_file

# Replace address with your AWS IoT endpoint
connection bridge-to-aws
address your-aws-endpoint.amazonaws.com:8883

# Replace these with actual paths to your downloaded certs
bridge_cafile /path/to/AmazonRootCA1.pem
bridge_certfile /path/to/certificate.pem.crt
bridge_keyfile /path/to/private.pem.key

bridge_insecure false
try_private false
cleansession true
start_type automatic
notifications false
log_type all

# Forward messages from local espresense topic to AWS IoT
topic espresense/devices/# out 0
