# Static network configuration snippet for setting a fixed IP address, gateway (router), and DNS servers for the Raspberry Pi's wlan0 interface (to be placed in /etc/dhcpcd.conf).
#
# Full tutorial: https://shillehtek.com/blogs/news/raspberry-pi-ssh-remote-access-external-network
# Shop parts: https://shillehtek.com
# More examples: https://github.com/shillehbean/shillehtek-examples
#

# Example static IP configuration:
interface wlan0
static ip_address=192.168.1.100/24
# Ensure this IP is on the same subnet as your router's IP
static routers=192.168.1.254
static domain_name_servers=192.168.1.254 8.8.8.8
