// Send the string "Hello from STM32H723!" over USART1 once per second using STM32 HAL initialization generated by STM32CubeMX.
//
// Buy this module: https://shillehtek.com/products/shillehtek-pre-soldered-stm32h723zgt6-core-development-board
// Full manual: https://shillehtek.com/blogs/shillehtek-product-manuals/shillehtek-pre-soldered-stm32h723zgt6-core-development-board-manual
// More examples: https://github.com/shillehtek/examples
//

// Generated with STM32CubeMX. After init code:

#include "main.h"
#include <string.h>

UART_HandleTypeDef huart1;

int main(void) {
  HAL_Init();
  SystemClock_Config();
  MX_GPIO_Init();
  MX_USART1_UART_Init();

  const char *msg = "Hello from STM32H723!\r\n";

  while (1) {
    HAL_UART_Transmit(&huart1, (uint8_t*)msg, strlen(msg), 100);
    HAL_Delay(1000);
  }
}
