# Squid configuration lines that define a local network ACL and allow HTTP access from that network.
#
# Full tutorial: https://shillehtek.com/blogs/news/raspberry-pi-squid-proxy-server-setup
# Shop parts: https://shillehtek.com
# More examples: https://github.com/shillehbean/shillehtek-examples
#

acl localnet src 192.168.1.0/24
http_access allow localnet
