# Kusto (ADX) command to create an 'iotdata' table schema for device telemetry.
#
# Full tutorial: https://shillehtek.com/blogs/news/raspberry-pi-pico-w-bme280-azure-iot-pipeline
# Parts used: https://shillehtek.com/products/bme280-pre-soldered-atmospheric-temperature-pressure-and-humidity-sensor
#             https://shillehtek.com/products/shillehtek-120pcs-multicolored-dupont-wire
#             https://shillehtek.com/products/shillehtek-120pcs-10cm-multicolored-jumper-wire
# More examples: https://github.com/shillehbean/shillehtek-examples
#

.create table iotdata (
  deviceId: string,
  temperature: real,
  humidity: real,
  pressure: real,
  timestamp: datetime
)
