# Example backend environment variables for the CAPTCHA secret key and JWT secret.
#
# Full tutorial: https://shillehtek.com/blogs/news/react-nodejs-recaptcha-secure-login
# Shop parts: https://shillehtek.com
# More examples: https://github.com/shillehbean/shillehtek-examples
#

CAPTCHA_SECRET_KEY=your-secret-key
JWT_SECRET=anything
