# Example frontend environment variable where the reCAPTCHA site key is stored for the React app.
#
# Full tutorial: https://shillehtek.com/blogs/news/react-nodejs-recaptcha-secure-login
# Shop parts: https://shillehtek.com
# More examples: https://github.com/shillehbean/shillehtek-examples
#

REACT_APP_CAPTCHA_SITE_KEY=your-site-key
